class PortfolioLoader{
  constructor(){this.projects=[];this.filteredProjects=[];this.currentFilter='all';this.categories=[]}
  async loadProjects(){const r=await fetch('/portfolio.json',{cache:'no-store'});if(!r.ok)throw new Error('Falha ao carregar portfolio.json');this.projects=await r.json();this.categories=[...new Set(this.projects.map(p=>p.categoria).filter(Boolean))].sort();this.filteredProjects=[...this.projects]}
  filterByCategory(c){this.currentFilter=c;this.filteredProjects=c==='all'?[...this.projects]:this.projects.filter(p=>p.categoria===c)}
  renderFilterButtons(){const g=document.getElementById('filterGroup');if(!g)return;g.innerHTML='';const cats=['all',...this.categories];cats.forEach(c=>{const b=document.createElement('button');b.className=`filter-btn ${this.currentFilter===c?'active':''}`;b.dataset.category=c;b.textContent=c==='all'?'Todos':c;b.addEventListener('click',()=>this.handleFilterClick(c));g.appendChild(b)})}
  handleFilterClick(c){document.querySelectorAll('.filter-btn').forEach(b=>b.classList.toggle('active',b.dataset.category===c));this.filterByCategory(c);this.renderGallery();document.dispatchEvent(new CustomEvent('portfolio:filtered',{detail:{filter:c}}))}
  safePath(p){if(!p)return '';return p.startsWith('/')?p:`/${p}`}
  createGalleryItem(p){const src=this.safePath(p.thumb||p.cover);return `<article class="gallery-item" data-project-id="${p.id}"><img src="${src}" alt="${this.escape(p.titulo)}" class="gallery-item-image" loading="lazy"><div class="gallery-overlay"><h3>${this.escape(p.titulo)}</h3><p>${this.escape(p.categoria||'')} • ${this.escape(p.ano||'')}</p></div></article>`}
  renderGallery(){const g=document.getElementById('galleryGrid');if(!g)return;if(!this.filteredProjects.length){g.innerHTML='<div class="empty-state"><h3 class="empty-state-title">Nenhum projeto encontrado</h3><p class="empty-state-text">Tente outra categoria.</p></div>';return}g.innerHTML=this.filteredProjects.map(p=>this.createGalleryItem(p)).join('');g.querySelectorAll('.gallery-item').forEach(item=>item.addEventListener('click',()=>location.href=`project.html?id=${encodeURIComponent(item.dataset.projectId)}`));window.portfolioAnimations?.reveal()}
  escape(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
  async initialize(){try{await this.loadProjects()}catch(e){console.error(e);document.getElementById('galleryGrid').innerHTML='<div class="empty-state"><h3 class="empty-state-title">Não foi possível carregar os projetos.</h3><p class="empty-state-text">Verifique o portfolio.json.</p></div>';return}if(window.PORTFOLIO_INITIAL_FILTER&&this.categories.includes(window.PORTFOLIO_INITIAL_FILTER))this.filterByCategory(window.PORTFOLIO_INITIAL_FILTER);this.renderFilterButtons();this.renderGallery();document.dispatchEvent(new CustomEvent('portfolio:rendered',{detail:{total:this.projects.length}}))}
}
window.portfolioLoader=new PortfolioLoader();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>window.portfolioLoader.initialize());else window.portfolioLoader.initialize();
